---
variables:
  IMAGE_NAME: poms/$CI_PROJECT_NAME
  REGISTRY: openshift-image-registry.apps.cluster.chp4.io

include:
  - project: 'npo-identity/poms/gitlab-templates'
    ref: 'chp4'
    file: 'docker_build.yml'
