---
variables:
  IMAGE_NAME: poms-plus/$CI_PROJECT_NAME
  REGISTRY: openshift-image-registry.apps.cluster.chp4.io

include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/6.1'
    file: 'docker_build.yml'
