---
variables:
  IMAGE_NAME: vpro/$CI_PROJECT_NAME
  REGISTRY: openshift-image-registry.apps.cluster.chp4.io

include:
  - project: 'shared/gitlab/gitlab-templates'
    ref: 'tags/4.21'
    file: 'docker_build.yml'
